In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, Bidirectional, GRU, Dense

In [3]:
input_text = [
    "The sun is shining brightly",
    "shining brightly in the blue",
    "brightly in the blue sky",
    "in the blue sky with",
    "the blue sky with few",
    "blue sky with few fluffy",
    "sky with few fluffy clouds"
]

In [4]:
#Tokenize input text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(input_text)
vocab_size = len(tokenizer.word_index) + 1
print("Vocabulary size:", vocab_size)

Vocabulary size: 13


In [5]:
#Convert input text to sequences
input_sequences = tokenizer.texts_to_sequences(input_text)

In [6]:
#pad input sequences
max_len = max(len(seq) for seq in input_sequences)
padded_sequences = pad_sequences(input_sequences, maxlen=max_len,padding='post')
print("Padded input sequences:", padded_sequences)

Padded input sequences: [[ 1 10 11  8  5]
 [ 8  5  6  1  2]
 [ 5  6  1  2  3]
 [ 6  1  2  3  4]
 [ 1  2  3  4  7]
 [ 2  3  4  7  9]
 [ 3  4  7  9 12]]


In [7]:
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=10, input_length=max_len-1),
    Bidirectional(GRU(128, return_sequences=True)),
    Bidirectional(GRU(128, return_sequences=True)),
    Dense(vocab_size, activation='softmax')
])

AttributeError: Exception encountered when calling layer 'forward_gru' (type GRU).

module 'tensorflow._api.v2.compat.v2.__internal__.function' has no attribute 'defun_with_attributes'

Call arguments received by layer 'forward_gru' (type GRU):
  • inputs=tf.Tensor(shape=(None, 4, 10), dtype=float32)
  • mask=None
  • training=None
  • initial_state=None

In [ ]:
# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

In [ ]:
# Train the model
X_data = padded_sequences[:, :-1]  # Input data (remove last word from each sequence)
y_data = padded_sequences[:, 1:]   # Output data (remove first word from each sequence)
model.fit(X_data, y_data, epochs=50, verbose=1)

In [ ]:
# Print input sequences and padded input sequences
print("Input sequences:", input_text)
print("Padded input sequences:", padded_sequences)

# Verify vocabulary size and index-word mapping
print("Vocabulary size:", vocab_size)
print("Index-word mapping:", tokenizer.index_word)

# Inspect the model's architecture
print(model.summary())